apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection
        image: fraud-detection:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        env:
        - name: APP_MODE
          value: "mlflow"
        - name: MLFLOW_TRACKING_URI
          value: "http://host.minikube.internal:5000"
        - name: FRAUD_THRESHOLD
          value: "0.45"
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "600Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
